name: Clear Database Daily

on:
  schedule:
    # Runs at 18:30 UTC (00:00 IST)
    - cron: '30 18 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  clear-database:
    runs-on: ubuntu-latest
    steps:
      - name: Clear database collections
        run: |
          curl -X POST "https://vibe.chaimine.com/api/clear-database?key=${{ secrets.CRON_SECRET_KEY }}"